### ISSUE TITLE
Feilmelding under sletting av application

### ISSUE THREAD

**Issue by Kyrremann** [nais/tobac#1]
Prøvde å slette en applikasjon:
```
$ k delete application gosys-nais
Error from server (InternalError): Internal error occurred: failed calling admission webhook "tobac.nais.io": Post https://tobac.nais.svc:443/?timeout=30s: stream error: stream ID 629557; INTERNAL_ERROR
```

Tobac-logg
```
{"level":"debug","msg":"attempting to fetch object from Kubernetes","time":"2019-01-14T11:11:10Z"}
{"level":"debug","msg":"using nais.io/v1alpha1, Resource=applications to look up resource 'gosys-nais' in namespace 'q1'","time":"2019-01-14T11:11:10Z"}
2019/01/14 11:11:10 http2: panic serving 192.168.112.0:58138: runtime error: invalid memory address or nil pointer dereference
goroutine 1613891 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc0001ae028, 0xc00055bfaf, 0xc0002b0380)
	/usr/local/go/src/net/http/h2_bundle.go:5870 +0x17c
panic(0xa9a740, 0x10f08f0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
main.reply(0xc0001d0900, 0x1d, 0x0, 0xc0002c4d40)
	/src/main.go:220 +0x42b
main.serve(0xc13360, 0xc0001ae028, 0xc0001d0900)
	/src/main.go:228 +0x40
net/http.HandlerFunc.ServeHTTP(0xb89f90, 0xc13360, 0xc0001ae028, 0xc0001d0900)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0x11006e0, 0xc13360, 0xc0001ae028, 0xc0001d0900)
	/usr/local/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc0001ce8f0, 0xc13360, 0xc0001ae028, 0xc0001d0900)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.initNPNRequest.ServeHTTP(0xc000067180, 0xc0001ce8f0, 0xc13360, 0xc0001ae028, 0xc0001d0900)
	/usr/local/go/src/net/http/server.go:3291 +0x8d
net/http.Handler.ServeHTTP-fm(0xc13360, 0xc0001ae028, 0xc0001d0900)
	/usr/local/go/src/net/http/h2_bundle.go:5592 +0x4d
net/http.(*http2serverConn).runHandler(0xc0002b0380, 0xc0001ae028, 0xc0001d0900, 0xc00016e200)
	/usr/local/go/src/net/http/h2_bundle.go:5877 +0x89
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5611 +0x4d3
```

Prøvde på nytt:
```
$ k delete application gosys-nais
Error from server (NotFound): applications.nais.io "gosys-nais" not found
```

**Comment by Kyrremann** [comment]
Nå funker det ja!
```
$ k delete application nais-testapp
Error from server: admission webhook "tobac.nais.io" denied the request: while retrieving resource: applications.nais.io "nais-testapp" not found
```
